### ISSUE TITLE
Create atomic module example

### ISSUE THREAD

**Issue by basham** [atomify/atomify-examples#1]
The Angular and Backbone examples are great introductions to an Atomify project. However, it would be helpful to have an example that aligns closer to @Techwraith's article [_Atomic Product Development_](http://techwraith.com/atomic-product-development.html).

In it, he discusses how to organize a molecule (Search Form) that depends on two atoms (Button and Form Input). It would be nice to have this written as a working example, instead of just in the article.

Further, I'd be really interested in understanding a best practice for managing these atomic modules, in at least relation to a live pattern library. Do you see each atom, molecule, organism, etc., being its own repo, so that you can establish NPM dependencies amongst them? If so, what's a good practice for updating these pieces? For example, in one part of the build process, I'd like the pattern library to automatically build a master CSS file from all styles associated with each of its pattern dependencies (created as a NPM package). Since NPM duplicates the content of packages at a version instead of cloning the git repo, how would I update, say, the Button atom styles in the pattern library (so I can live see them affect both the Button and Search Form) and later commit those changes to their respective repo? Committing changes to the Button repo outside of the pattern library and reinstalling it via NPM would be a very cumbersome process to see the affect of a few changes. Any thoughts on how to do this better?

**Comment by basham** [comment]
It seems like the answer to my pattern-as-a-package concern is probably resolved by using [`npm link`](https://www.npmjs.org/doc/cli/npm-link.html). Never used this before, but looks incredibly promising.

If `npm link` is the recommendation for pattern libraries that depend on packaged patterns, then perhaps it would be good to describe that process in some doc, especially since Atomify is so strongly associated with Atomic Design.

**Comment by techwraith** [comment]
So this is what we do for this at Getable:

All modules are kept in the same repo under a "components" directory. These
modules reference each other using relative paths. In your case I would
create a separate directory called "pattern-lib-site" or something that has
it's own atomified bundles for css and js. This should allow you to put
together a simple page for each component, as well as a catch all
"components" list.

npm link is also a good option, but it requires a bit more set up than I
prefer.

**Comment by bclinkinbeard** [comment]
Lots of good points and questions here. 

Regarding the example from the article, @Techwraith actually built it with an older version of Atomify, and I plan to update and publish it soon. It was simply faster and easier to adapt my Angular demo to Backbone, and I was eager to get the announcement post out. 

Regarding the larger question, I agree that keeping things in the same repo, at least initially, makes sense. Once they get to a point where you feel it makes sense to split them out, I also wouldn't hesitate to do that. 

npm link could be useful for the initial phase of splitting things out, and also for times of active development when committing, pushing, and updating would be annoying. 

Once things are more stable, I think having them in their own repo with ^ semantic versioning makes a lot of sense too, especially if they will be used in multiple contexts/projects. Part of that stabilization process is/should be recognizing the parts of the atom that should be configurable and defining an API to accommodate that. The initial post didn't mention it, but CSS variable support is built in, so even your style atoms can allow (optional) external customization. 

HTH,
Ben

**Comment by basham** [comment]
Thanks all for the suggestions. I have a much better idea of my approach, now. Will start playing soon.

@bclinkinbeard Looking forward to updates, as they happen.

**Comment by bclinkinbeard** [comment]
I pushed an updated (and simplified) version of this last night as [themed-search-forms](https://github.com/atomify/atomify-examples/tree/master/themed-search-forms). It shows how to create multiple, varied instances of a component, as well as how to build a differently "themed" version.

**Comment by basham** [comment]
Excellent. I really enjoy seeing the interaction among and variations of the components. Quite helpful.
