### ISSUE TITLE
Angular sample - browserify bundle.js file output issue

### ISSUE THREAD

**Issue by mikekidder** [atomify/atomify-examples#2]
Somewhere in atomify process it's concatenating the HTML string with **module.exports =** twice.   Not sure if it's atomify, or partialify doing that.

{"./DemoController":2,"./template.html":4}],4:[function(require,module,exports){
module.exports = '`module.exports = \'`<div>\n  Static template content\n\n  <ul class="pList">\n   <li ng-repeat="item in list">{{ item.name }}</li>\n  </ul>\n\n <button ng-click="showMessage()">Show Message</button>\n</div>\n`\';`';}

**Comment by ben-ng** [comment]
Ive seen this happen if you require a module with a relative path that has a package.json with transforms specified.

Is that what you're doing?

**Comment by bclinkinbeard** [comment]
I just pushed an update that should fix this. Thanks for catching it, and let us know if you still have issues after pulling and `npm install`ing.

**Comment by mikekidder** [comment]
Fixed now. Thanks!
